[dev]
localhost ansible_connection=local

[bastion]
# bastion ansible_host=1.2.3.4 ansible_user=ec2-user

[ci_runners]
# runner1 ansible_host=10.0.1.10 ansible_user=ubuntu

[all:vars]
ansible_python_interpreter=auto_silent
